name: rock_classify
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21
  - pandas>=1.3
  - scikit-learn=1.7.1
  - xgboost>=1.6
  - catboost>=1.1
  - lightgbm>=3.3
  - imbalanced-learn>=0.9
  - shap>=0.41
  - matplotlib>=3.5
  - seaborn>=0.11
  - tqdm>=4.64
  - numba>=0.55
  - llvmlite>=0.38
  - joblib=1.5.1
  - scikit-image=0.20.0
  - pip
  - pip:
      - jinja2>=3.0
      - reportlab>=3.6
